name: Build Dimasik APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK with Buildozer Action
      uses: ArtemGovorov/buildozer-action@v1
      with:
        buildozer_version: stable
        command: buildozer android debug
